version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:15.3
    restart: always
    ports: 
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    healthcheck:
        test: "psql -U postgres"
        interval: 3s
        timeout: 3s
        retries: 100
        start_period: 10s
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
